
[2023, 8, 18, 15, 44, 10] :;: 25864 :;: ['  File "<stdin>", line 1, in <module>\n', '  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load\n', '  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked\n', '  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked\n', '  File "<frozen importlib._bootstrap_external>", line 940, in exec_module\n', '  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1290, in <module>\n    log.crash(os.getpid())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 27, in crash\n    log.data.append([pytools.clock.getDateTime(), str(strf), str(traceback.format_stack())])\n']
[2023, 8, 18, 15, 44, 23] :;: dnwbella.mp3, 100 :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1194, in register\n    printDebug(path + ", " + str(volume))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 59, in printDebug\n    log.crash(strf)\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 27, in crash\n    log.data.append([pytools.clock.getDateTime(), str(strf), str(traceback.format_stack())])\n']
[2023, 8, 18, 15, 44, 27] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    test = int(pytools.IO.getFile("soundCount.cx"))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 27, in crash\n    log.data.append([pytools.clock.getDateTime(), str(strf), str(traceback.format_stack())])\n']
[2023, 8, 18, 15, 44, 27] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FC862880>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    test = int(pytools.IO.getFile("soundCount.cx"))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 45, 58] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    try:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 45, 58] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    try:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 51, 35] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.wave import WAVE\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 51, 35] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.wave import WAVE\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 52, 9] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.wave import WAVE\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 52, 9] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.wave import WAVE\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 53, 18] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.mp3 import MP3\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 53, 18] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    from mutagen.mp3 import MP3\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    error = 0\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 54, 53] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    try:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 54, 53] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    try:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 59, 56] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    else:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 15, 59, 56] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    else:\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    log.crash("Unexpected error:", sys.exc_info())\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 16, 7, 3] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 18, 16, 7, 3] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 0, 35] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 0, 35] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 0, 43] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 0, 43] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "speed": speed,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 1, 43] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "volume": volume,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    return xmltodict.parse(pytools.IO.getFile(path, doPrint=doPrint))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 1, 43] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "volume": volume,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    return xmltodict.parse(pytools.IO.getFile(path, doPrint=doPrint))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 1, 47] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "volume": volume,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    return xmltodict.parse(pytools.IO.getFile(path, doPrint=doPrint))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 1, 47] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "volume": volume,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    return xmltodict.parse(pytools.IO.getFile(path, doPrint=doPrint))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 2, 39] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 2, 39] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FCC63440>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 2, 40] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 2, 40] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FC8C5EC0>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: Uncaught exception :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 73, in exception_handler\n    pytools.IO.appendFile(".\\\\logs\\\\today\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + message + " :;: " + callStack.replace("\\n", "    \\\\n\\t"))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: Type: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 74, in exception_handler\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: <class 'NameError'> :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 74, in exception_handler\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: Value: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 75, in exception_handler\n    def printDebug(strf):\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: name 'pytools' is not defined :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 75, in exception_handler\n    def printDebug(strf):\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: Traceback: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 76, in exception_handler\n    log.crash(strf)\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 1] :;: <traceback object at 0x000001F3FC8C5EC0> :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 76, in exception_handler\n    log.crash(strf)\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: Uncaught exception :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 73, in exception_handler\n    pytools.IO.appendFile(".\\\\logs\\\\today\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + message + " :;: " + callStack.replace("\\n", "    \\\\n\\t"))\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: Type: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 74, in exception_handler\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: <class 'NameError'> :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 74, in exception_handler\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: Value: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 75, in exception_handler\n    def printDebug(strf):\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: name 'pytools' is not defined :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 75, in exception_handler\n    def printDebug(strf):\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: Traceback: :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 76, in exception_handler\n    log.crash(strf)\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 5, 9] :;: <traceback object at 0x000001F3FCAE8280> :;: ['  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 76, in exception_handler\n    log.crash(strf)\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 36] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 36] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FC32BA00>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 52] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 52] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FFADD600>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 53] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 19, 3, 8, 53] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FFADD600>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 20, 3, 0, 36] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 20, 3, 0, 36] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FFADD600>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 20, 3, 0, 37] :;: Unexpected error: :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']
[2023, 8, 20, 3, 0, 37] :;: (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x000001F3FFADD600>) :;: ['  File "<stdin>", line 1, in <module>\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 1265, in run\n    "path": ".\\\\sound\\\\assets\\\\" + path,\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 233, in getFile\n    import xmltodict\n', '  File "C:\\Users\\joshp\\Desktop\\deffered_audio_client\\modules\\audio.py", line 43, in crash\n    pytools.IO.appendFile(".\\\\logs\\\\errors\\\\" + log.dateString + "\\\\event_" + log.timeString + ".log", "\\n" + str(dateArray) + " :;: " + str(strf) + " :;: " + str(traceback.format_stack()).replace("\\n", "    \\\\n\\t"))\n']